In [10]:
import numpy as np
import pandas as pd

pd.Series(3.14)
pd.Series(3.14, index=['A','B','C'])

A    3.14
B    3.14
C    3.14
dtype: float64

In [17]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

In [22]:
import numpy as np
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [32]:
z = np.zeros((2,3,4))
z

array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [84]:
import numpy as np
r = np.arange(6).reshape(((3,2)))
r

array([[0, 1],
       [2, 3],
       [4, 5]])

In [106]:
alist = []
b = np.arange(28).reshape(4,7)
print(b.ndim)
for x in b:
    for y in x:
        alist.append(y)
print(alist)

2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

In [107]:
a = np.arange(28).reshape(4,7)
alist = []
alist = list(a.flat)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

In [134]:
import pandas as pd
import numpy as np

r = np.arange(100,200).reshape(2,50)
print(r)
r = r.flat
srs = pd.Series(list(r))
srs.to_csv('out.csv')#Users/AppleDocuments/Programming/Python/Udemy/Python\ Pandas\ Data\ Science\ for\ Beginners_Alan\ Yue/out.csv')
print(srs)

[[100 101 102 ..., 147 148 149]
 [150 151 152 ..., 197 198 199]]
0     100
1     101
2     102
3     103
4     104
5     105
6     106
7     107
8     108
9     109
10    110
11    111
12    112
13    113
14    114
15    115
16    116
17    117
18    118
19    119
20    120
21    121
22    122
23    123
24    124
25    125
26    126
27    127
28    128
29    129
     ...
70    170
71    171
72    172
73    173
74    174
75    175
76    176
77    177
78    178
79    179
80    180
81    181
82    182
83    183
84    184
85    185
86    186
87    187
88    188
89    189
90    190
91    191
92    192
93    193
94    194
95    195
96    196
97    197
98    198
99    199
Length: 100, dtype: int64

In [135]:
import pandas as pd
import numpy as np

data = pd.read_csv('out.csv')
data

     0  100
0    1  101
1    2  102
2    3  103
3    4  104
4    5  105
5    6  106
6    7  107
7    8  108
8    9  109
9   10  110
10  11  111
11  12  112
12  13  113
13  14  114
14  15  115
15  16  116
16  17  117
17  18  118
18  19  119
19  20  120
20  21  121
21  22  122
22  23  123
23  24  124
24  25  125
25  26  126
26  27  127
27  28  128
28  29  129
29  30  130
..  ..  ...
69  70  170
70  71  171
71  72  172
72  73  173
73  74  174
74  75  175
75  76  176
76  77  177
77  78  178
78  79  179
79  80  180
80  81  181
81  82  182
82  83  183
83  84  184
84  85  185
85  86  186
86  87  187
87  88  188
88  89  189
89  90  190
90  91  191
91  92  192
92  93  193
93  94  194
94  95  195
95  96  196
96  97  197
97  98  198
98  99  199

[99 rows x 2 columns]